export const nationalities = [
    "Saudi Arabia",
    "Egypt",
    "Jordan",
    "Syria",
    "Lebanon",
    "Palestine",
    "Kuwait",
    "UAE",
    "Qatar",
    "Bahrain",
    "Oman",
    "Yemen",
    "Iraq",
    "Sudan",
    "Morocco",
    "Tunisia",
    "Algeria",
    "Libya",
    "Pakistan",
    "India",
    "Philippines",
    "Bangladesh",
    "Nepal",
    "Sri Lanka",
    "Indonesia",
    "USA",
    "UK",
    "Canada",
    "France",
    "Germany",
    "Other"
];
